### ISSUE TITLE
Traducteur

### ISSUE THREAD

**Issue by IzadZ** [nodejs/nodejs-fr#91]
Bonjour,

J'aimerais aidé à la traduction. Quel est le process à suivre ?

**Comment by cedced19** [comment]
@nodejs/i18n can you help us ? @IzadZ wants to join translation team

**Comment by kapouer** [comment]
@IzadZ "quand deux verbes se suivent, le deuxième se met toujours à l'infinitif".

**Comment by Raul6469** [comment]
Ce n'est pas toujours le cas @kapouer : "j'avais aidé" et non "j'avais aider" 😉

**Comment by maddhruv** [comment]
@IzadZ 
please check - https://github.com/nodejs/i18n#joining if you want to join the team
or
check - https://crowdin.com/project/nodejs if you want to help with the translations
